version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  pedidos-service:
    build:
      context: ./PedidosService
    container_name: pedidos-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=sqlserver;Database=PedidosDB;User Id=sa;Password=YourStrong!Password;TrustServerCertificate=True;
    ports:
      - "5121:5121"
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
